"""init_table_creation

Revision ID: c2780757a01f
Revises: 
Create Date: 2025-04-08 17:31:25.414051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy.vector import VECTOR
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'c2780757a01f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('record_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('Countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('record_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('Locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('record_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['Countries.country_id'], ),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('city', 'country', name='unique_location_city_country')
    )
    op.create_table('Jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('workplace_type', sa.String(length=10), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('job_state', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.String(length=255), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('apply_link', sa.Text(), nullable=True),
    sa.Column('embedding', VECTOR(dim=1024), nullable=True),
    sa.Column('portal', sa.String(length=255), nullable=True),
    sa.Column('record_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Companies.company_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['Locations.location_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'apply_link', name='unique_location_apply_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Jobs')
    op.drop_table('Locations')
    op.drop_table('Countries')
    op.drop_table('Companies')
    # ### end Alembic commands ###
