"""made job_id a foreign key

Revision ID: 073f610858ab
Revises: 502869596fa4
Create Date: 2025-09-23 18:42:09.415813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073f610858ab'
down_revision: Union[str, None] = '502869596fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rejected_jobs', 'Jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rejected_jobs', type_='foreignkey')
    # ### end Alembic commands ###
