"""added fields tables

Revision ID: e59ccfe84933
Revises: c2780757a01f
Create Date: 2025-06-15 22:12:40.396618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59ccfe84933'
down_revision: Union[str, None] = 'c2780757a01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root_field', sa.String(length=255), nullable=False),
    sa.Column('sub_field', sa.String(length=255), nullable=False),
    sa.Column('record_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FieldJobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['Fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['Jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'field_id')
    )
    op.drop_column('Jobs', 'field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('field', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('FieldJobs')
    op.drop_table('Fields')
    # ### end Alembic commands ###
